
import DATABASE.Myconnection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class addnewfligh extends javax.swing.JFrame {
  PreparedStatement pst=null;

    /**
     * Creates new form addnewflight
     */
    public addnewfligh() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        add_flight = new javax.swing.JButton();
        dates = new com.toedter.calendar.JDateChooser();
        fid = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        fcharge = new javax.swing.JTextField();
        dest = new javax.swing.JComboBox<>();
        src = new javax.swing.JComboBox<>();
        dept = new javax.swing.JTextField();
        arv = new javax.swing.JTextField();
        Delete_flight = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Deoarture:-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Add New Flight");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Source:-");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Flight_Id:-");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Departure_Time:-");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Flight_Charges:-");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Flight_Name:-");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Arrival_Time:-");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Destination:-");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Date Of Departure:-");

        add_flight.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        add_flight.setForeground(new java.awt.Color(0, 0, 255));
        add_flight.setText("Add Flight");
        add_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_flightActionPerformed(evt);
            }
        });

        dates.setForeground(new java.awt.Color(0, 0, 255));
        dates.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        fid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fid.setForeground(new java.awt.Color(0, 0, 255));
        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });

        fname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 255));

        fcharge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fcharge.setForeground(new java.awt.Color(0, 0, 204));

        dest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dest.setForeground(new java.awt.Color(0, 0, 255));
        dest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Port Blair\t", "Visakhapatnam Airport\t", "Hyderabad\t", "Guwahati\t", "New Delhi\t", "Dabolim (Village)", "Ahmedabad\t", "Bengaluru\t", "Mangalore", "Kochi", "Kozhikode", "Thiruvananthapuram", "Mumbai", "Nagpur", "Imphal", "Bhubaneswar", "Amritsar", "Jaipur", "Chennai", "Coimbatore", "Tiruchirapalli", "Lucknow", "Varanasi\t", "Kolkata\t", "Gaya", "Surat", "Vadodara\t", "Srinagar", "Kannur", "Pune", "Ranchi", "Siliguri" }));
        dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destActionPerformed(evt);
            }
        });

        src.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        src.setForeground(new java.awt.Color(0, 0, 255));
        src.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Port Blair\t", "Visakhapatnam Airport\t", "Hyderabad\t", "Guwahati\t", "New Delhi\t", "Dabolim (Village)", "Ahmedabad\t", "Bengaluru\t", "Mangalore", "Kochi", "Kozhikode", "Thiruvananthapuram", "Mumbai", "Nagpur", "Imphal", "Bhubaneswar", "Amritsar", "Jaipur", "Chennai", "Coimbatore", "Tiruchirapalli", "Lucknow", "Varanasi\t", "Kolkata\t", "Gaya", "Surat", "Vadodara\t", "Srinagar", "Kannur", "Pune", "Ranchi", "Siliguri" }));

        dept.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dept.setForeground(new java.awt.Color(0, 0, 255));

        arv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        arv.setForeground(new java.awt.Color(0, 0, 255));

        Delete_flight.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Delete_flight.setForeground(new java.awt.Color(0, 0, 255));
        Delete_flight.setText("Delete  Flight");
        Delete_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_flightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(add_flight, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                        .addComponent(jLabel10))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(src, 0, 257, Short.MAX_VALUE)
                                    .addComponent(dept))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fname)
                    .addComponent(dest, 0, 225, Short.MAX_VALUE)
                    .addComponent(arv)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Delete_flight, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_flight, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_flight, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_flightActionPerformed
           String flightid = fid.getText();
           String flname = fname.getText();
           String value = src.getSelectedItem().toString();
           String value1 = dest.getSelectedItem().toString();
           String depta = dept.getText();
           String arvs=arv.getText();
           String flcharge=fcharge.getText();
           String bdate=null;
           if(dates.getDate()!=null){
           SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
           bdate=dateformat.format(dates.getDate());
           }
           
          if("".equals(flightid))
            {
            JOptionPane.showMessageDialog(null, "Add Flight ID. ");
            }
            else if("".equals(flname))
            {
            JOptionPane.showMessageDialog(null, "Add Flight Name. ");
            }
           else if("".equals(depta))
            {
            JOptionPane.showMessageDialog(null, "Add Departure Time. ");
            }
           else if("".equals(arvs))
            {
            JOptionPane.showMessageDialog(null, "Add Arrival Time. ");
            }
           else if("".equals(flcharge))
            {
            JOptionPane.showMessageDialog(null, "Add Flight Charge. ");
            }else if("".equals(bdate))
            {
            JOptionPane.showMessageDialog(null, "Add Date of Journey. ");
            }
           else
           {
        
        String  Query;
                Query="SELECT * FROM `add_flight` WHERE `F_ID`='"+flightid+"'";
            String query;
            query="INSERT INTO `add_flight`"
                    +"(`F_ID`, `F_NAME`, `SOURCE`, `DESTINATION`, `DEPARTURE`, `ARRIVAL`, `F_CHARGE`, `DOD`) "
                    +"VALUES (?,?,?,?,?,?,?,?)";
               try {
                   pst=Myconnection.getConnection().prepareStatement(Query);
                  ResultSet rs=pst.executeQuery();
                   if(rs.next())
                   {
                   JOptionPane.showMessageDialog(null, "This Flight Id is Already Exists. ");
                   }
                   else
                   {
                   pst=Myconnection.getConnection().prepareStatement(query);
                   pst.setString(1,flightid);
                   pst.setString(2, flname);
                   pst.setString(3, value);
                   pst.setString(4, value1);
                   pst.setString(5, depta);
                   pst.setString(6, arvs);
                   pst.setString(7, flcharge);
                   pst.setString(8,bdate );
                   if(bdate!=null)
                       {
                                  pst.setString(8, bdate);
                       }
                       else
                      {
                       pst.setNull(8, 0);
                      }
                       if(pst.executeUpdate()>0)
                       {
                       JOptionPane.showMessageDialog(null, "Flight added sucessfully");
                       }
                   }
                   fid.setText("");
                   fid.requestFocus();
                   fname.setText("");
                   fname.requestFocus();
                   dept.setText("");
                   arv.requestFocus();
                   fcharge.setText("");
                   fcharge.requestFocus();
                   fid.setText("");
                   fid.requestFocus();
                   dept.setText("");
                   dept.requestFocus();
                   arv.setText("");
                   arv.requestFocus();
               }
        catch (SQLException ex) {
            Logger.getLogger(addnewflight.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addnewflight.class.getName()).log(Level.SEVERE, null, ex);
        }
               }        

    }//GEN-LAST:event_add_flightActionPerformed

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed

    private void destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destActionPerformed
     
    }//GEN-LAST:event_destActionPerformed

    private void Delete_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_flightActionPerformed
      
        try{
           String  sql2="DELETE FROM `add_flight` WHERE F_ID=?";
          pst=Myconnection.getConnection().prepareStatement(sql2);
           pst.setString(1,fid.getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "deleted Successfully");
           
       }
       catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
       } catch (ClassNotFoundException ex) {
            Logger.getLogger(addnewflight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_flightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addnewflight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addnewflight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addnewflight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addnewflight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addnewflight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_flight;
    private javax.swing.JButton add_flight;
    private javax.swing.JTextField arv;
    private com.toedter.calendar.JDateChooser dates;
    private javax.swing.JTextField dept;
    private javax.swing.JComboBox<String> dest;
    private javax.swing.JTextField fcharge;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> src;
    // End of variables declaration//GEN-END:variables
}
