
import DATABASE.Myconnection;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class HOMEPAGE extends javax.swing.JFrame {
ResultSet rs=null;
    /**
     * Creates new form HOMEPAGE
     */
    public HOMEPAGE() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        faceboook = new javax.swing.JButton();
        instagram = new javax.swing.JButton();
        loc = new javax.swing.JButton();
        twitter = new javax.swing.JButton();
        google = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        addnewflight = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        viewflight = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        help1 = new javax.swing.JMenu();
        abus = new javax.swing.JMenuItem();
        ctus = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 0));

        welcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(0, 153, 0));
        welcome.setText("Welcome to Airlines...........");
        welcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        faceboook.setBackground(new java.awt.Color(51, 51, 255));
        faceboook.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        faceboook.setForeground(new java.awt.Color(255, 255, 255));
        faceboook.setText("Go to Facebook");
        faceboook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faceboookActionPerformed(evt);
            }
        });

        instagram.setBackground(new java.awt.Color(0, 0, 255));
        instagram.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        instagram.setForeground(new java.awt.Color(255, 255, 255));
        instagram.setText("Go to Instagram");
        instagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instagramActionPerformed(evt);
            }
        });

        loc.setBackground(new java.awt.Color(0, 0, 255));
        loc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        loc.setForeground(new java.awt.Color(255, 255, 255));
        loc.setText("Go to Location");
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });

        twitter.setBackground(new java.awt.Color(0, 0, 255));
        twitter.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        twitter.setForeground(new java.awt.Color(255, 255, 255));
        twitter.setText("Go to Twitter");
        twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterActionPerformed(evt);
            }
        });

        google.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/google.png"))); // NOI18N
        google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nip.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(welcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(faceboook, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(google, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(195, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(instagram)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(faceboook, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(instagram, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(loc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(google, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 51));

        jMenu3.setBackground(new java.awt.Color(0, 0, 255));
        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 0), new java.awt.Color(0, 255, 0)));
        jMenu3.setForeground(new java.awt.Color(255, 0, 204));
        jMenu3.setText("Manager Details        ");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        addnewflight.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        addnewflight.setBackground(new java.awt.Color(255, 255, 0));
        addnewflight.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addnewflight.setForeground(new java.awt.Color(0, 0, 255));
        addnewflight.setText("Add New Customers");
        addnewflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewflightActionPerformed(evt);
            }
        });
        jMenu3.add(addnewflight);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem2.setText("View Control");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem3.setText("Add New Flight");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        viewflight.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_MASK));
        viewflight.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewflight.setForeground(new java.awt.Color(0, 0, 204));
        viewflight.setText("View Flight");
        viewflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewflightActionPerformed(evt);
            }
        });
        jMenu3.add(viewflight);

        jMenuBar1.add(jMenu3);

        jMenu1.setBackground(new java.awt.Color(0, 0, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 0), new java.awt.Color(0, 204, 0)));
        jMenu1.setForeground(new java.awt.Color(255, 0, 204));
        jMenu1.setText("Ticket Windows           ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem1.setText("Make Reservation");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 0, 204));
        jMenuItem4.setText("Ticket Enquiry");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem5.setText("Cancel Ticket");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 51), new java.awt.Color(0, 255, 51)));
        jMenu2.setForeground(new java.awt.Color(255, 0, 153));
        jMenu2.setText("Account           ");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setBackground(new java.awt.Color(255, 255, 0));
        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem6.setText("Booking List");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(0, 0, 255));
        jMenuItem7.setText("Flight List");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("LogOut");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu2.add(logout);

        jMenuBar1.add(jMenu2);

        help1.setForeground(new java.awt.Color(255, 0, 153));
        help1.setText("  About Us  and Contact Us                ");
        help1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        help1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help1ActionPerformed(evt);
            }
        });

        abus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        abus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        abus.setForeground(new java.awt.Color(0, 0, 255));
        abus.setText("About Us");
        abus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abusActionPerformed(evt);
            }
        });
        help1.add(abus);

        ctus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        ctus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ctus.setForeground(new java.awt.Color(0, 0, 255));
        ctus.setText("Contact Us");
        ctus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctusActionPerformed(evt);
            }
        });
        help1.add(ctus);

        jMenuBar1.add(help1);

        jMenu4.setForeground(new java.awt.Color(255, 0, 102));
        jMenu4.setText("Help             ");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        help.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        help.setForeground(new java.awt.Color(0, 0, 255));
        help.setText("Help");
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });
        jMenu4.add(help);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addnewflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewflightActionPerformed
        addnewcustomers lgn=new addnewcustomers();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
        
    }//GEN-LAST:event_addnewflightActionPerformed

    private void faceboookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faceboookActionPerformed
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.facebook.com/"));
        }
        catch(IOException err)
        {

        }
        catch (URISyntaxException ex) {
            Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_faceboookActionPerformed

    private void instagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instagramActionPerformed
       Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.instagram.com/"));
        }
        catch(IOException err)
        {

        }
        catch (URISyntaxException ex) {
            Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instagramActionPerformed

    private void twitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterActionPerformed
        Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://twitter.com/"));
        }
        catch(IOException err)
        {

        }
        catch (URISyntaxException ex) {
            Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_twitterActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
       Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.google.com/maps"));
        }
        catch(IOException err)
        {

        }
        catch (URISyntaxException ex) {
            Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_locActionPerformed

    private void googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleActionPerformed
         Desktop browser=Desktop.getDesktop();
        try{
            browser.browse(new URI("https://www.google.com"));
        }
        catch(IOException err)
        {

        }
        catch (URISyntaxException ex) {
            Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_googleActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       viewcutomers lgn=new viewcutomers();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        addnewflight lgn=new  addnewflight();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
      
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void viewflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewflightActionPerformed
       viewflight lgn=new  viewflight();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_viewflightActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       ticketenquiry lgn=new  ticketenquiry ();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ticketreservation lgn=new   ticketreservation();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       cancelticket lgn=new   cancelticket ();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        bookinglist lgn=new   bookinglist ();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         flightlist lgn=new   flightlist ();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    
      LoginPage lgn=new  LoginPage ();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void help1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help1ActionPerformed
        
    }//GEN-LAST:event_help1ActionPerformed

    private void abusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abusActionPerformed
       AboutUs lgn=new AboutUs();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_abusActionPerformed

    private void ctusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctusActionPerformed
        ContactUs lgn=new ContactUs();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_ctusActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
       Help lgn=new Help();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.MAXIMIZED_HORIZ);
    }//GEN-LAST:event_helpActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        PreparedStatement pst;
        String query="SELECT * FROM `register` WHERE `Usertype`=\"Admin\"";
        try{
      pst=Myconnection.getConnection().prepareStatement(query);
                        rs=pst.executeQuery();
                        if(rs.next())
                        {
                        JOptionPane.showMessageDialog(null,"You are a admin.");
                        }
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(HOMEPAGE.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOMEPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOMEPAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abus;
    private javax.swing.JMenuItem addnewflight;
    private javax.swing.JMenuItem ctus;
    private javax.swing.JButton faceboook;
    private javax.swing.JButton google;
    private javax.swing.JMenuItem help;
    private javax.swing.JMenu help1;
    private javax.swing.JButton instagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loc;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton twitter;
    private javax.swing.JMenuItem viewflight;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
