
import DATABASE.Myconnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 
 */
public class ticketreservation extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    private Object JTable1;
    String filename=null;
    String roll;
    /**
     * Creates new form makereservation
     */
    public ticketreservation() {
        initComponents();
        roll="";
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupbutton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dest = new javax.swing.JComboBox<>();
        src = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ftable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tno = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        dates2 = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        adr = new javax.swing.JTextArea();
        fid = new javax.swing.JTextField();
        fname1 = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        byname = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        fcharge = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        dates = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        seats = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        BOOK = new javax.swing.JButton();
        fclass = new javax.swing.JComboBox<>();
        gender = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Ticket Reservation");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Source:-");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Destination:-");

        dest.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dest.setForeground(new java.awt.Color(0, 0, 255));
        dest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Port Blair\t", "Visakhapatnam Airport\t", "Hyderabad\t", "Guwahati\t", "New Delhi\t", "Dabolim (Village)", "Ahmedabad\t", "Bengaluru\t", "Mangalore", "Kochi", "Kozhikode", "Thiruvananthapuram", "Mumbai", "Nagpur", "Imphal", "Bhubaneswar", "Amritsar", "Jaipur", "Chennai", "Coimbatore", "Tiruchirapalli", "Lucknow", "Varanasi\t", "Kolkata\t", "Gaya", "Surat", "Vadodara\t", "Srinagar", "Kannur", "Pune", "Ranchi", "Siliguri" }));

        src.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        src.setForeground(new java.awt.Color(0, 0, 255));
        src.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Port Blair\t", "Visakhapatnam Airport\t", "Hyderabad\t", "Guwahati\t", "New Delhi\t", "Dabolim (Village)", "Ahmedabad\t", "Bengaluru\t", "Mangalore", "Kochi", "Kozhikode", "Thiruvananthapuram", "Mumbai", "Nagpur", "Imphal", "Bhubaneswar", "Amritsar", "Jaipur", "Chennai", "Coimbatore", "Tiruchirapalli", "Lucknow", "Varanasi\t", "Kolkata\t", "Gaya", "Surat", "Vadodara\t", "Srinagar", "Kannur", "Pune", "Ranchi", "Siliguri" }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Select Flight from List Given Below");

        ftable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ftable.setForeground(new java.awt.Color(0, 0, 255));
        ftable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight_Id", "Flight_Name", "Departue", "Date Of Departure", "FLight_Charges"
            }
        ));
        jScrollPane1.setViewportView(ftable);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Search by Name List");

        ctable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ctable.setForeground(new java.awt.Color(0, 0, 255));
        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer_Id", "Customer_Name", "Father's_Name", "Gender", "DOB", "Address"
            }
        ));
        jScrollPane2.setViewportView(ctable);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Ticket_Number:-");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Customer_Id:-");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Customer_Name:-");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Father's_Name:-");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("D_O_B:-");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Gender:-");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Address:-");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Flight_Id:-");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Departure_Time:-");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Flight_Name:-");

        tno.setEditable(false);
        tno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tno.setForeground(new java.awt.Color(255, 0, 0));
        tno.setText("1");
        tno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnoActionPerformed(evt);
            }
        });

        cid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cid.setForeground(new java.awt.Color(0, 204, 0));

        cname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cname.setForeground(new java.awt.Color(0, 204, 0));

        fname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 204, 0));

        dates2.setForeground(new java.awt.Color(0, 204, 0));
        dates2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        adr.setColumns(20);
        adr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adr.setForeground(new java.awt.Color(0, 204, 0));
        adr.setRows(5);
        jScrollPane3.setViewportView(adr);

        fid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fid.setForeground(new java.awt.Color(0, 0, 204));

        fname1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fname1.setForeground(new java.awt.Color(0, 0, 204));

        dept.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dept.setForeground(new java.awt.Color(0, 204, 0));

        SEARCH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SEARCH.setForeground(new java.awt.Color(0, 0, 255));
        SEARCH.setText("Search");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        byname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        byname.setForeground(new java.awt.Color(0, 0, 255));
        byname.setText("Search By Name");
        byname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bynameActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Amount:-");

        fcharge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fcharge.setForeground(new java.awt.Color(0, 0, 255));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Date Of Journey:-");

        dates.setForeground(new java.awt.Color(0, 0, 255));
        dates.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Flight_Charges:-");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Flight_Class:-");

        seats.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        seats.setForeground(new java.awt.Color(204, 0, 204));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Seats:-");

        amt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        amt.setForeground(new java.awt.Color(204, 0, 204));

        BOOK.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        BOOK.setForeground(new java.awt.Color(0, 0, 255));
        BOOK.setText("Book");
        BOOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKActionPerformed(evt);
            }
        });

        fclass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fclass.setForeground(new java.awt.Color(204, 0, 204));
        fclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "First Class", "Business Class", "Premium Economy class", "Economy Class " }));

        gender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(269, 269, 269)
                                            .addComponent(jLabel4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(53, 53, 53))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel15))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fid)
                                        .addComponent(fname1)
                                        .addComponent(dept)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(gender, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(fname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cname, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cid, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dates2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(243, 243, 243)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(byname, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOOK, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dates, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fcharge, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fclass, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1)
                                .addComponent(SEARCH)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(byname)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dates, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(gender))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dates2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fclass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seats, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(BOOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
           
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showTableData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bynameActionPerformed
         showTableData1();
    }//GEN-LAST:event_bynameActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
          String custid=cid.getText();
        if(custid.equals(""))
        {
        JOptionPane.showMessageDialog(null, "Add customer id");
        }
        else
        {
        
        try{
           String  sql="SELECT * FROM cuntomerdetail WHERE CUSTOMER_ID=?";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false","root","@nitesh@123@");
           pst=con.prepareStatement(sql);
           pst.setString(1,cid.getText());
           rs=pst.executeQuery();
           while(rs.next())
           {
           cname.setText(rs.getString("CUSTOMER_NAME"));
           fname.setText(rs.getString("FATHER_NAME"));
           gender.setText(rs.getString("GENDER"));
           dates2.setDate(rs.getDate("DATE_OF_BIRTH"));
           adr.setText(rs.getString("ADDRESS"));
            
           }
          
       }
       catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
       }
        }
        
        String flightid=fid.getText();
        if(flightid.equals(""))
        {
        JOptionPane.showMessageDialog(null, "Add flight id");
        }
        else
        {
        
        try{
           String  sql="SELECT * FROM `add_flight` WHERE F_ID=?";
           con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false","root","@nitesh@123@");
           pst=con.prepareStatement(sql);
           pst.setString(1,fid.getText());
           rs=pst.executeQuery();
           
           while(rs.next())
           {
           fname1.setText(rs.getString("F_NAME"));
           dept.setText(rs.getString("DEPARTURE"));
           fcharge.setText(rs.getString("F_CHARGE"));
           dates.setDate(rs.getDate("DOD"));
           }
       }
       catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null, ex);
       }
        }       
    }//GEN-LAST:event_SEARCHActionPerformed

    private void BOOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKActionPerformed
        String T_NOs=tno.getText();
        String s = tno.getText();
        int billNumber = Integer.valueOf(s);
        s = Integer.toString(++billNumber);
        tno.setText(s);
        String flightid=fid.getText();
        String seat=seats.getText();
        
         if("".equals(T_NOs))
            {
            JOptionPane.showMessageDialog(null, "Add Ticket Number. ");
            }else
         {
        PreparedStatement pst;
        String  Query;
                Query="SELECT * FROM `booking` WHERE `T_NO`='"+T_NOs+"'";
                String Query1="SELECT * FROM `booking` WHERE `F_ID`='"+flightid+"' AND  `SEATS`='"+seat+"'";
            String query;
            query="INSERT INTO `booking`"
                    +"(`T_NO`, `CUST_ID`, `CUST_NAME`, `ADDRESS`, `F_ID`, `F_NAME`, `DOJ`, `SOURCE`, `DESTINATION`, `F_CHAREG`, `F_CLASS`, `SEATS`) "
                    +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

            try {
                pst=Myconnection.getConnection().prepareStatement(Query);
                  ResultSet rs1=pst.executeQuery();
                   if(rs1.next())
                   {
                   JOptionPane.showMessageDialog(null, "This Ticket number is Already Exists. ");
                   }
                  
                  pst=Myconnection.getConnection().prepareStatement(Query1);
                  rs1=pst.executeQuery();
                   if(rs1.next())
                   {
                   JOptionPane.showMessageDialog(null, "On this flight id this seat  is Already booked. ");
                   }     
            
                   else
                   {
                pst=Myconnection.getConnection().prepareStatement(query);
                pst.setString(1, T_NOs);
                pst.setString(2, cid.getText());
                pst.setString(3,cname.getText());
                pst.setString(4, adr.getText());
                pst.setString(5, flightid);
                pst.setString(6, fname1.getText());
                String bdate=null;
            if(dates.getDate()!=null)
            {
                SimpleDateFormat dateformat=new SimpleDateFormat("yyyy-MM-dd");
                bdate=dateformat.format(dates.getDate());
            }
            if(bdate!=null)
                {
                    pst.setString(7, bdate);
                }
                else
                {
                    pst.setNull(7, 0);
                }
               pst.setString(8, src.getSelectedItem().toString());
               pst.setString(9, dest.getSelectedItem().toString());
               pst.setString(10, fcharge.getText());
               pst.setString(11, fclass.getSelectedItem().toString());
               pst.setString(12, seat);
               
                if(pst.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null, "Book sucessfully");
                }
            }
                 
                   cid.setText("");
                   cid.requestFocus();
                   cname.setText("");
                   cname.requestFocus();
                   fname.setText("");
                   fname.requestFocus();
                   adr.setText("");
                   adr.requestFocus();
                   fid.setText("");
                   fid.requestFocus();
                   dept.setText("");
                   dept.requestFocus();
                   fname1.setText("");
                   fname1.requestFocus();
                   gender.setText("");
                   gender.requestFocus();
                   fcharge.setText("");
                   fcharge.requestFocus();
                   seats.setText("");
                   seats.requestFocus();
                   amt.setText("");
                   amt.requestFocus();
            }catch (SQLException ex) {
                Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(RegisterPage.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_BOOKActionPerformed

    private void tnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnoActionPerformed
     
    }//GEN-LAST:event_tnoActionPerformed
public void showTableData(){
try{
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false","root","@nitesh@123@");
String sql="SELECT `F_ID`, `F_NAME`, `DEPARTURE`,`F_CHARGE`, `DOD` FROM `add_flight` WHERE SOURCE=? AND DESTINATION=?;";
pst=con.prepareStatement(sql);
pst.setString(1,src.getSelectedItem().toString());
pst.setString(2, dest.getSelectedItem().toString());
rs=pst.executeQuery();
ftable.setModel(DbUtils.resultSetToTableModel(rs));

}
catch(SQLException ex){
JOptionPane.showMessageDialog(null, ex);
}
}
public void showTableData1(){
try{
con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project?autoReconnect=true&useSSL=false","root","@nitesh@123@");
String sql="SELECT `CUSTOMER_ID`, `CUSTOMER_NAME`, `FATHER_NAME`, `GENDER`, `DATE_OF_BIRTH`, `ADDRESS` FROM `cuntomerdetail` WHERE CUSTOMER_NAME=?";
pst=con.prepareStatement(sql);
pst.setString(1,cname.getText());
rs=pst.executeQuery();
ctable.setModel(DbUtils.resultSetToTableModel(rs));

}
catch(SQLException ex){
JOptionPane.showMessageDialog(null, ex);
}
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketreservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOK;
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextArea adr;
    private javax.swing.JTextField amt;
    private javax.swing.JButton byname;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JTable ctable;
    private com.toedter.calendar.JDateChooser dates;
    private com.toedter.calendar.JDateChooser dates2;
    private javax.swing.JTextField dept;
    private javax.swing.JComboBox<String> dest;
    private javax.swing.JTextField fcharge;
    private javax.swing.JComboBox<String> fclass;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fname1;
    private javax.swing.JTable ftable;
    private javax.swing.JTextField gender;
    private javax.swing.ButtonGroup groupbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField seats;
    private javax.swing.JComboBox<String> src;
    private javax.swing.JTextField tno;
    // End of variables declaration//GEN-END:variables
}
